create table public.chat
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    title      varchar(255)
);

alter table public.chat
    owner to postgres;

create table public.chat_entry
(
    id         bigint generated by default as identity
        primary key,
    content    text,
    created_at timestamp(6),
    role       varchar(255)
        constraint chat_entry_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ASSISTANT'::character varying])::text[])),
    chat_id    bigint
        constraint fkqcc1bnu77jh530e61twlq52ja
            references public.chat
);

alter table public.chat_entry
    owner to postgres;

